title: Cafer Poyrazoğlu
author:
  name: Cafer Poyrazoğlu
  email: cafererhan@gmail.com

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: CaferPoyrazoglu
    github: CaferPoyrazoglu
    linkedin: cafer-poyrazoglu

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
